//
//  UserIdentityViewController.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class UserProfileViewController: UIViewController {
    
    @IBOutlet weak var userImageView: UIImageView!
    @IBOutlet weak var userName: UILabel!
    @IBOutlet weak var userID: UILabel!
    @IBOutlet weak var userEmailAddress: UILabel!
    
    // MARK: - View lifecycle
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)

        let identityManager = AWSIdentityManager.defaultIdentityManager()
        
        // Load username to profile
        if let identityUserName = identityManager.userName {
            userName.text = identityUserName
        } else {
            userName.text = NSLocalizedString("Guest User", comment: "Placeholder text for the guest user.")
        }
        
        // Load user img to profile
        userID.text = identityManager.identityId
        if let imageURL = identityManager.imageURL {
            let imageData = NSData(contentsOfURL: imageURL)!
            if let profileImage = UIImage(data: imageData) {
                userImageView.image = profileImage
            } else {
                userImageView.image = UIImage(named: "UserIcon")
            }
        }
        
        //TODO
        // Load email address to user profile
        //userEmailAddress.text = identityManager.e
        
    }
    
    @IBAction func Settings(sender: UIButton) {
        let storyboard = UIStoryboard(name: "UserSettings", bundle: nil)
        let viewController = storyboard.instantiateViewControllerWithIdentifier("UserSettings")
        navigationController!.pushViewController(viewController, animated: true)
    }
    /* Abandon
    func getProfile(){
    
        
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        queryExpression.keyConditionExpression = "#hashAttribute = :hashAttributeWithComplexName"
        queryExpression.expressionAttributeNames = ["#hashAttribute": "EmailAddress"]
        queryExpression.expressionAttributeValues = [":hashAttribute": "xu.1487"]
        
        
        objectMapper.query(UserProfileTableRow.self, expression: queryExpression) .continueWithExecutor(AWSExecutor.mainThreadExecutor(), withBlock: { (task:AWSTask!) in
            if (task.error == nil) {
                if (task.result != nil) {
                    let tableRow = task.result as! UserProfileTableRow
                    
                    self.userEmailAddress.text = tableRow.EmailAddress
                }
            }
            else {
                self.userEmailAddress.text = task.error.debugDescription
            }
            return nil
        })
    }
 */
}
