//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
// Edited by: Kee Sern Chua


import UIKit
import AWSMobileHubHelper

class PracticesViewController: UITableViewController {
    
    var demoFeatures: [DemoFeature] = []
    var signInObserver: AnyObject!
    var signOutObserver: AnyObject!
    var willEnterForegroundObserver: AnyObject!
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
       navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .Plain, target: nil, action: nil)

        var demoFeature = DemoFeature.init(
            name: NSLocalizedString("Level 1",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("",
                comment: "Description for demo menu option."),
            icon: "IconLessons", storyboard: "Level1")
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Level 2",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("",
                comment: "Description for demo menu option."),
            icon: "IconLessons", storyboard: "Level2")
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Level 3",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("",
                comment: "Description for demo menu option."),
            icon: "IconLessons", storyboard: "Level3")
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Level 4",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("",
                comment: "Description for demo menu option."),
            icon: "IconLessons", storyboard: "Level4")
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Level 5",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("",
                comment: "Description for demo menu option."),
            icon: "IconLessons", storyboard: "Level5")
        
        demoFeatures.append(demoFeature)
        
    }

    
    // MARK: - UITableViewController delegates
    
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("MainViewCell")!
        let demoFeature = demoFeatures[indexPath.row]
        cell.imageView!.image = UIImage(named: demoFeature.icon)
        cell.textLabel!.text = demoFeature.displayName
        cell.detailTextLabel!.text = demoFeature.detailText
        return cell
    }
    
    override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return demoFeatures.count
    }
    
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
        let demoFeature = demoFeatures[indexPath.row]
        let storyboard = UIStoryboard(name: demoFeature.storyboard, bundle: nil)
        let viewController = storyboard.instantiateViewControllerWithIdentifier(demoFeature.storyboard)
        self.navigationController!.pushViewController(viewController, animated: true)
        /*
        let vc = self.storyboard?.instantiateViewControllerWithIdentifier("VideoViewController")
        self.presentViewController(vc! as UIViewController, animated: true, completion: nil)
 */
    }
    

}
    


