# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MySampleApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleAPIClient/Drive'
  pod 'GTMOAuth2'
  # Pods for MySampleApp

end
