//
//  AEPStudents.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class AEPStudents: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _noteId: String?
    var _content: String?
    var _creationDate: NSNumber?
    var _title: String?
    
    class func dynamoDBTableName() -> String {

        return "aepios-mobilehub-1099679197-AEP-Students"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_noteId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_noteId" : "noteId",
               "_content" : "content",
               "_creationDate" : "creationDate",
               "_title" : "title",
        ]
    }
}
